const express = require('express');                                                       // Importation d'Express pour créer l'application web. Express est un framework web pour Node.js qui facilite la gestion des requêtes HTTP, le routage, les middlewares, etc.
const cors = require('cors');                                                             // Importation de CORS pour gérer les requêtes cross-origin. C'est à dire des requêtes provenant d'un domaine différent de celui du serveur. Ainsi, on peut autoriser ou restreindre l'accès aux ressources du serveur en fonction de l'origine des requêtes.
const app = express();                                                                    // Création de l'application Express
require("./../db/mongo.js");                                                              // Connexion à la base de données MongoDB

app.use(cors());                                                                          // Activation de CORS pour toutes les routes de l'application. Cela permet à des applications front-end hébergées sur des domaines différents d'accéder aux ressources de ce serveur.
app.use(express.json());                                                                  // Middleware pour parser le corps des requêtes en JSON. Ainsi, les données envoyées dans le corps des requêtes HTTP (comme les requêtes POST ou PUT) seront automatiquement converties en objets JavaScript accessibles via req.body. par exemple, si une requête POST envoie un JSON { "name": "John" }, on pourra accéder à ce nom via req.body.name.
app.use('/api/' + process.env.IMAGES_PUBLIC_URL, express.static(process.env.IMAGES_FOLDER));  // Configuration du dossier pour servir les fichiers statiques (images). On dit ici :"Pour toute requête vers /images/*, sers les fichiers du dossier uploads/". Les fichiers seront accessibles via l'URL définie par IMAGES_PUBLIC_URL. Par exemple, si IMAGES_PUBLIC_URL est "images" et IMAGES_FOLDER est "uploads", une image stockée dans "uploads/picture.jpg" sera accessible via "http://yourserver/images/picture.jpg".  

module.exports = { app };